language: node_js
node_js:
- node
before_install:
- npm i -g npm@4.1.2
install:
- npm install
cache:
  directories:
  - node_modules
deploy:
  provider: script
  skip_cleanup: true
  script: travis_deployment/deploy.sh
  on:
    branch: master
addons:
  ssh_known_hosts: open-player.dynu.net
before_install:
- openssl aes-256-cbc -K $encrypted_59494d185558_key -iv $encrypted_59494d185558_iv
  -in travis_deployment/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa 
